apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-07-09T09:59:44Z"
  labels:
    app: nginx
    app.kubernetes.io/instance: nginx
  name: nginx
  namespace: nginx-test
  resourceVersion: "10272"
  selfLink: /api/v1/namespaces/nginx-test/services/nginx
  uid: a7ef0d9c-fd94-49ae-a060-d4fa83f65a7f
spec:
  clusterIP: 10.101.179.249
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30148
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
