apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    app.kubernetes.io/instance: nginx
  name: nginx
  namespace: nginx-test
spec:
  clusterIP: 10.101.179.249
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30148
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
